# Generated by Django 4.2.15 on 2025-03-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='discryption',
            new_name='description',
        ),
    ]
