# Generated by Django 4.2.15 on 2025-04-20 11:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_discryption_advertisement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU')),
            ],
            bases=('posts.post',),
        ),
    ]
